# Makefile

all : reclist recarrays

reclist : reclinkedlist.cpp linkedlist.h
	g++ -std=c++11 reclinkedlist.cpp -o reclist

recarrays : recarrays.cpp 
	g++ -std=c++11 recarrays.cpp -o recarrays

clean:
	rm reclist recarrays

